### ISSUE TITLE
Publish to maven repostiory

### ISSUE THREAD

**Issue by jgoldhammer** [OrderOfTheBee/ootbee-support-tools#1]
Can you please publish this to a maven repository so that others are able to  include this as a module?

Thanks
Jens

**Comment by AFaust** [comment]
I was planning on it - at the moment I am basically just waiting for the last tool (scheduled jobs) to be added by Sujay Pillai who started to work on it at the end of the hackathon.

**Comment by AFaust** [comment]
Short update: The addon JS code has been cleaned up, scheduled jobs tool has been included and the JSHint execution has been standardized on the Acosix jshint-maven-plugin (published as 1.0.0 to Maven Central today). I will discuss the matter of releasing the addon itself to Maven Central (specifically the question of how the Order of the Bee wants to handle ownership of the org.orderofthebee namespace in Maven Central) in our next board meeting on Thursday.

**Comment by AFaust** [comment]
A SNAPSHOT version of the addon was published to artifacts.orderofthebee.org yesterday via the automated Jenkins build. Publishing to Maven Central was discussed during a board meeting on Thursday and will be pursued in this week.

**Comment by AFaust** [comment]
@binduwavell It hasn't actually been published to Maven Central yet. The current SNAPSHOT has been published to Sonatype OSS.

**Comment by AFaust** [comment]
Finally, the 0.0.1.0 version is [published on Maven Central](http://search.maven.org/#search%7Cga%7C1%7Corg.orderofthebee.support-tools)
