### ISSUE TITLE
Thread dump analyzer

### ISSUE THREAD

**Issue by angelborroy-ks** [OrderOfTheBee/ootbee-support-tools#102]
## ENHANCEMENT

Integrating an Analyzer tool for Thread Dump like [https://github.com/spotify/threaddump-analyzer](https://github.com/spotify/threaddump-analyzer) should increase current feature usability.

**Comment by binduwavell** [comment]
We use this analyzer a lot at Zia. Would be great if at least the thread dumps were formatted like `jstack -l` Output so such tools can be used. A deeper integration would be even cooler :)

**Comment by AFaust** [comment]
I am wondering what the relevant differences are about our current thread dump format and jstack -l.
Testing it locally on Alfresco 5.2 / Oracle JDK 1.8.0_144 I see:

* missing empty line between last stack frame and "locked ownable synchronizers"
* missing thread deamon status, priority, OS priority, tid, nid, and instead showing times blocked, waited etc.
* missing detail of WAITING state (e.g. "parking")
* missing native threads (e.g. C2 compiler, parallel GC threads)
* information about global JNI references

Which of these differences would need to be addressed to be compatible with the Spotify analyzer? We may not be able to get access to all the information from within a running Java process via regular APIs (excluding e.g. Unsafe utilities).

**Comment by AFaust** [comment]
Testing with a thread dump retrieved from our tooling, I can currently only get the Spotify analyzer to detect a single thread, but there is no indication which issues prevent better detection.

**Comment by binduwavell** [comment]
I wonder if this is “the source” for jstack: http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/7-b147/sun/tools/jstack/JStack.java
