### ISSUE TITLE
Provide the Brazilian Portuguese translation for the SOLR Tracking

### ISSUE THREAD

**Issue by douglascrp** [OrderOfTheBee/ootbee-support-tools#109]
## FEATURE / ENHANCEMENT

The corrent version of this addon does not provide the Brazilian Portuguese translation for the brand new SOLR Tracking feature.

I am going to work on this and create a PR as soon as it is done.

**Comment by AFaust** [comment]
@douglascrp is this still an issue that you are working on or did it get superseded by work priorities?

**Comment by douglascrp** [comment]
@AFaust It is something I am working in parts. When I have some free minutes, I edit one or two files.
It is not forgoten, if it is what you want to know.
