### ISSUE TITLE
Cache page doesn't work - Invalid JSON response

### ISSUE THREAD

**Issue by luca86r** [OrderOfTheBee/ootbee-support-tools#114]
## BUG
Error accessing cache page:
![selezione_061](https://user-images.githubusercontent.com/2351488/38256581-ea1e6530-375e-11e8-984a-8cf0b13c96da.png)

### Expected behavior
View cache data

### Actual behavior
No cache data showed

### Steps to reproduce the behavior
Access OOTB cache page

### Additional details (analysis so far, log statements, references, etc.)
The service /s/ootbee/admin/caches return an invalid JSON response: [cache.json.txt](https://github.com/OrderOfTheBee/ootbee-support-tools/files/1872004/cache.json.txt)
As you can see, JSON content is invalid because decimal numbers use comma as decimal separator. I think this is due to the locale of my server: it_IT (in Italy, comma is the decimal separator).

### Tell us about your environment
Client OS: Ubuntu 14.04 LTS (64bit)
Browser: Chrome 65.0.3325.181 (Build ufficiale) (a 64 bit)
Server OS: Ubuntu 14.04 LTS (64bit)
DB: PostgreSQL 9.4

**Comment by AFaust** [comment]
Did you try with the latest SNAPSHOT? This issue was already addressed in #106

**Comment by luca86r** [comment]
You're right, the snapshot version fixes this bug.
