### ISSUE TITLE
Cannot find file in repository

### ISSUE THREAD

**Issue by errmerrged** [OrderOfTheBee/ootbee-support-tools#118]
## BUG
I was going to build the project locally but I am getting an error when downloading the resources from the repository.
This is the Error I am getting:
`Could not resolve dependencies for project org.orderofthebee.support-tools:support-tools-repo:amp:1.1.0.0-SNAPSHOT: Failure to find org.springframework.social:spring-social-facebook:jar:1.0.0.RC1 in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of ossrh has elapsed or updates are forced`

### Expected behavior
I am expecting to generate the AMP files for the repo and share projects

### Actual behavior
cannot build the project because of this issue

### Steps to reproduce the behavior
I am using windows to build the project, so I opened CMD then browsed to the home folder and run `mvn install`

### Tell us about your environment
I am currenty using Windows 10 in just building the amp files and will transfer them later on to our linux server where Alfresco resides.

**Comment by boiss007** [comment]
tested with the commited code today (debian 9) and it worked as intended : 
`[INFO] Reactor Summary:
[INFO]
[INFO] OOTBee Support Tools - Parent ...................... SUCCESS [  0.376 s]
[INFO] OOTBee Support Tools - Repository Module ........... SUCCESS [04:27 min]
[INFO] OOTBee Support Tools - Share Module ................ SUCCESS [ 35.955 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:04 min
[INFO] Finished at: 2018-07-17T12:49:10+02:00
[INFO] Final Memory: 67M/1425M
[INFO] ------------------------------------------------------------------------
`

**Comment by errmerrged** [comment]
H
[disconnect_a_user_error.txt](https://github.com/OrderOfTheBee/ootbee-support-tools/files/2208520/disconnect_a_user_error.txt)
i @boiss007 also tried the last commit by @AFaust but I'm having issues when I try to disconnect a user. I am getting an error, I am using Alfresco CE 5.1 , see attached file. But will wait for the official release when the commit is merged with the main branch, maybe they'll fix this.


Regards,
Law

**Comment by Yash0182** [comment]
Is there a good read on all this, where I can learn these minute details about maven and how builds happen?
