### ISSUE TITLE
add links to amp downloads

### ISSUE THREAD

**Issue by ainsofs** [OrderOfTheBee/ootbee-support-tools#148]
Hi,

Just a suggestion can we add links to the amps in the release notes? Took me a while to find them as Im not familiar with maven central

share amp
https://repo1.maven.org/maven2/org/orderofthebee/support-tools/support-tools-share/1.1.0.0/support-tools-share-1.1.0.0-amp.amp

alfresco amp
https://repo1.maven.org/maven2/org/orderofthebee/support-tools/support-tools-repo/1.1.0.0/support-tools-repo-1.1.0.0-amp.amp

**Comment by AFaust** [comment]
So far the release notes do not contain any links to binary artifacts, so neither for JARs nor AMPs. The only artifacts included in teh release notes are what GitHub automatically attaches (source code archives).  If we include links, it probably should be links to either all the artifacts or the global entry point, e.g. https://repo1.maven.org/maven2/org/orderofthebee/support-tools/

**Comment by ainsofs** [comment]
ahh right. I wonder how its done here: https://github.com/Alfresco/alfresco-support-tools/releases

**Comment by AFaust** [comment]
It is also possible to upload / attach the files directly / explicitely to the release notes. I just have not done that for OOTBee Support Tools so far because I don't like redundancy / wasting of resources (even if it's just a few MiB on highly commoditized storage).

**Comment by yregaieg** [comment]
I am closing this issue since we now have a link in the project readme for https://search.maven.org/search?q=g:org.orderofthebee.support-tools containing download links for the different versions of the addon.
