### ISSUE TITLE
Error on the Scheduled Jobs tool

### ISSUE THREAD

**Issue by douglascrp** [OrderOfTheBee/ootbee-support-tools#172]
### Expected behavior

When the user opens the Scheduled Jobs tool, he should see the list of scheduled jobs

### Actual behavior

A 500 error is generated

### Steps to reproduce the behavior

Simply access the Scheduled Jobs tool and the error appears.

### Additional details (analysis so far, log statements, references, etc.)

The Web Script /alfresco/s/ootbee/admin/scheduled-jobs has responded with a status of 500 - Internal Error.

500 Description:	An error inside the HTTP server which prevented it from fulfilling the request.
 
Message:	04180007 Wrapped Exception (with status template): 04180025 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js': 04180024 TypeError: Cannot call property instanceDefinitionFor in object [JavaPackage com.cronutils.model.definition.CronDefinitionBuilder]. It is not a function, it is "object". (classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js#247)
Server:	Community v6.1.1 (r9d03d2fd-b168) schema 12.001

### Tell us about your environment

Alfresco Community 6.1.1
Support Tools 1.1.0 and 1.2.0-SNAPSHOT (same problem in both versions)
JVM - v1.8.0_252-8u252-b09-1~18.04-b09;
Ubuntu 18.04

**Comment by AFaust** [comment]
Are some 3rd-party addons or customisations with jobs installed? Alfresco 6.1.1 also does not exist as either a EA or GA release, so appears to have been some weird development snapshot. Does the problem occur on a proper 6.1.2 GA as well?

**Comment by douglascrp** [comment]
Hello.

The version I'm using is the version installed by Loftux script https://github.com/loftuxab/alfresco-ubuntu-install

About the addons/customizations, no, I don't have any.

I have not tested it against the 6.1.2 GA.

**Comment by AFaust** [comment]
I tested with the current 1.2.0.0-SNAPSHOT from master branch on 6.1.2 GA. I cannot find a general issue with OOTBee Support Tools on that version, and cannot think of anything that would break the functionality in that code line. Considering that 6.1.1 was an early access version, I am planning to close this issue. @douglascrp Do you aggree?
