### ISSUE TITLE
Cache page doesn't print when locale is fr

### ISSUE THREAD

**Issue by laborima** [OrderOfTheBee/ootbee-support-tools#175]
## BUG

Under caches.get.json

${cacheInfo.cacheMissRate?string["0.#"]}

Will give 1,2in french because decimal separator is coma. It will break json output.

Setting  <#setting locale="en">  into the webscript will fix the issue 

Regards

**Comment by yregaieg** [comment]
Thanks for raising that to our attention. Would you please issue a PR with the fix?
I will try to have a look at it next week :-)

**Comment by AFaust** [comment]
We already have a PR for this: https://github.com/OrderOfTheBee/ootbee-support-tools/pull/173
