### ISSUE TITLE
Add reset dashboard - Dashboard Management

### ISSUE THREAD

**Issue by loftux** [OrderOfTheBee/ootbee-support-tools#21]
Sometimes the Share user dashboard gets corrupted. Or you just want the users to start over.
Add a feature to reset the dashboard for an individual user or all users.

Here is some sample code on how it can be done
http://alfresco.blog.redpill-linpro.com/2014/06/12/resetting-a-users-dashboard-in-alfresco-share/

Can also be useful for a similar feature for site dashboards.

**Comment by AFaust** [comment]
That SurfConfigCleaner policy is among the worst examples of class inheritance I have seen in a long time. It is not just a policy - it is a fully fledged RemoteStore and can be used for god-knows-what. And all that just for 2 reused operations / ~15 LoC that could have been copied. Shame on the responsible Alfresco engineer(s).

I agree that resetting a dashboard is a potentially useful feature. Unfortunately the approach outlined for user dashboards won't work for sites which are not initialized on first access like the user dashboard. Also any tool we would provide has to take care of data still in Surf caches inside of Share. So ideally this would be a Share-tier tool in the "Admin Tools" menu and only use the Surf API exposed to Share. That would also allow us to handle site dashboards differently, e.g. by using the PresetsManager to re-construct a site dashboard from the preset that is currently valid.

One other feature I have pondered about with regards to this is the ability to globally remove (or modify) all configured instances of a specific dashlet, e.g. the RSS Feed. I recently did a migration where some Community-provided dashlets no longer are included as they are incompatible with the new Alfresco version. For this I used a JavaScript Console script to find and delete all the component XMLs from the Alfresco Repository, and was forced to restart Share to ensure caches are cleared.

**Comment by AFaust** [comment]
I have added an action to reset site dashboards to the current preset default to the Sites Manager / Sites Console tool. Additionally there is a new Dashboard Components tool to individually filter and delete dashlets. Currently it does not support paging yet which might be problematic for larger systems...

**Comment by AFaust** [comment]
Pagination has been added in commit https://github.com/OrderOfTheBee/ootbee-support-tools/commit/e4cebbf34d48fd10aa3cceb2a473b4bf81f5b114.
The only thing missing now would be reset of a user dashboard as a whole.
