### ISSUE TITLE
Alfresco 23.1 AMP Files

### ISSUE THREAD

**Issue by marcokonsultex** [OrderOfTheBee/ootbee-support-tools#217]
Hi Axel,

do you have the ampś files of ootbee-support-tools of Alfresco 23.1?

I don´t find in this website. Only 1.2.1. I read that you build of new version.

Thanks.

Marco

**Comment by AFaust** [comment]
The branch for the ACS 23.1 compatibility has not been merged yet and so there are no pre-built artifacts available yet. But the branch for ACS 23.1 is public as https://github.com/AFaust/ootbee-support-tools/tree/ACS-23.1-compat and you can build the SNAPSHOT artifacts from it.

**Comment by AFaust** [comment]
There are two PRs that I'd like to merge in the release. As my work and private life is quite busy at the moment, I think it will be sometime in April at the earliest that a release can be expected.

**Comment by AFaust** [comment]
I have finalised the [1.2.2.0 release](https://github.com/OrderOfTheBee/ootbee-support-tools/releases/tag/1.2.2.0) - the AMPs should be available in Maven Central shortly.
