### ISSUE TITLE
Webscript 500 error when using the scheduled jobs tool.

### ISSUE THREAD

**Issue by douglascrp** [OrderOfTheBee/ootbee-support-tools#224]
## BUG

Webscript 500 error when using the scheduled jobs tool.

### Expected behavior

The list of scheduled jobs should be shown.

### Actual behavior

Web Script Status 500 - Internal Error

The Web Script [/alfresco/s/ootbee/admin/scheduled-jobs](https://myserver.com.br/alfresco/s/ootbee/admin/%2Falfresco%2Fs%2Footbee%2Fadmin%2Fscheduled-jobs) has responded with a status of 500 - Internal Error.

500 Description:	An error inside the HTTP server which prevented it from fulfilling the request.
 
Message:	07130017 Wrapped Exception (with status template): 07130408 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js': 07130407 TypeError: Cannot call property instanceDefinitionFor in object [JavaPackage com.cronutils.model.definition.CronDefinitionBuilder]. It is not a function, it is "object". (classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js#247)
Server:	Community schema 18.000

### Steps to reproduce the behavior

Just click on the tool.

### Additional details (analysis so far, log statements, references, etc.)

Logs: https://pastebin.com/u3Nzmk5R

### Tell us about your environment

Alfresco Community 7.4.0.1
Support Tools 1.2.2.0

**Comment by AFaust** [comment]
Is this reproducible in an out-of-the-box Alfresco with only OOTBee Support Tools? I am using scheduled jobs all the time in various Alfresco versions (7.3, 7.4, and 23.2 as well), and have not encountered this yet. We did update cron-utils from 5.0.3 to 9.1.6 as result of a dependabot PR end of 2022 (for 1.2.0.0 of this module), but then again that has been in use for quite a while already....

**Comment by douglascrp** [comment]
I'm not sure, but I can give it a try and let you know when it's done.

**Comment by douglascrp** [comment]
Answering again, actually, we have been using it with Alfresco 7.4 too, and it really works.
This makes me wonder what can be causing this issue with this specific server.
I will investigate it

**Comment by cleseach** [comment]
Hello Douglas,
Isn't your problem related to this closed issue: https://github.com/OrderOfTheBee/ootbee-support-tools/issues/145 ?

**Comment by AFaust** [comment]
Thanks @cleseach for that potential hint - I had not considered it because I know @douglascrp and did not consider a simple mistake as a potential explanation.
