### ISSUE TITLE
Enable all tools for all editions of Alfresco

### ISSUE THREAD

**Issue by AFaust** [OrderOfTheBee/ootbee-support-tools#29]
As discussed in the kick-off session for the OOTBee maintainers on January 6th, we want to enable all tools to be displayed in any edition of Alfresco. We acknowledge the overlap this may produce with the Alfresco Support Tools addon but since a few of the tools have been significantly improved compared to that addon, it would be a shame if the tools cannot be used just due to our reluctance. Maybe we can add a customisation / optional label suffix to visually separate these tools when both addons have been installed at the same time.

**Comment by AntonioSoler** [comment]
Hi,
If you download the Early Build for Alfresco 5.2 Enterprise you may notice that my code is now installed by default. (Yes! It has been merged with the alfresco repo jar). Please keep that in mind just in case in the future someone may try to install the ootb version on top of an Enterprise

**Comment by AFaust** [comment]
Thanks @AntonioSoler, that is good to know. Since I no longer have ready access to all Enterprise builds - not to meantion EA - I would not have noticed that soon. That means the differentiation via menu labels becomes more important...
