### ISSUE TITLE
Webscript service for consuming metrics from external sources

### ISSUE THREAD

**Issue by CesarCapillas** [OrderOfTheBee/ootbee-support-tools#52]
Hi:

First of all, thank you for the addon. It is very useful also for monitoring Alfresco Community.
I would like to request for an enhacement. I monitor Alfresco with nagios/icinga and I wonder if it was possible to collect some of the metrics information in a webscript for being consumed in JSON format from external sources:
 - Active database connections
 - Active tickets in Alfresco
 - Logged users
 - CPU used
 - Memory used 
 - Number of threads
 - ...

Thanks in advance and best regards.

--C.

**Comment by AFaust** [comment]
Does it have to be a single web script with all the metrics? Because currently those metrics that are displayed in a graph are already loaded via a JSON web script - only that there is a web script for each tool, so e.g. the "Active Sessions" and the "System Performance" tools each have their own.

**Comment by AFaust** [comment]
Current web scripts for metrics: [active-sessions.get](https://github.com/OrderOfTheBee/ootbee-support-tools/blob/master/repository/src/main/amp/config/alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/active-sessions.get.desc.xml), [active-sessions-updateUsers.get](https://github.com/OrderOfTheBee/ootbee-support-tools/blob/master/repository/src/main/amp/config/alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/active-sessions-update-users.get.desc.xml), [performance.get](https://github.com/OrderOfTheBee/ootbee-support-tools/blob/master/repository/src/main/amp/config/alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/performance.get.desc.xml)
)

**Comment by CesarCapillas** [comment]
Thank you Axel, now I can see them, that's great. 
I checked the webscripts in /alfresco/service/index but I only saw them in html format.

- /alfresco/service/ootbee/admin/admin-performance?format=json
- /alfresco/service/ootbee/admin/active-sessions?format=json
- /alfresco/service/ootbee/admin/active-sessions-updateUsers

Thanks and best regards.

--C.
